export const cardAdder = (arr, container) => {
  arr.forEach(({ title, description, image, linkProject }) => {
    const projectTitle = title;
    const projectDescription = description;
    const imageSrc = image;
    const link = linkProject;
    const imagee = document.createElement("img");
    const aTag = document.createElement("a");
    const button = document.createElement("button");
    const paragraph = document.createElement("p");
    const titlee = document.createElement("h1");
    const projectCard = document.createElement("div");
    const projectImageDiv = document.createElement("div");
    const projectContent = document.createElement("div");
    imagee.src = imageSrc;
    titlee.textContent = projectTitle;
    paragraph.textContent = projectDescription;
    aTag.target = "_blank";
    aTag.href = link;
    aTag.textContent = "Checkout";
    button.append(aTag);
    projectCard.className = "project-card";
    projectImageDiv.className = "project-card-image";
    projectContent.className = "project-card-content";
    imagee.id = "image-id";
    projectImageDiv.append(imagee);
    projectContent.append(titlee);
    projectContent.append(paragraph);
    projectContent.append(button);
    projectCard.append(projectImageDiv);
    projectCard.append(projectContent);
    container.append(projectCard);
  });
};
